# Generated by Django 2.2.1 on 2019-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='activities', to='users.Activity'),
        ),
    ]
