# Generated by Django 2.2.1 on 2019-11-24 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191123_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
