# Generated by Django 2.2.1 on 2019-11-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191123_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
