version: '2'

services:

  django:
    env_file: .env
    build: ./django
    command: bash -c "python manage.py runserver 0:8000"
    volumes:
      - ./django:/django
    

  nginx:
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - django
