# Generated by Django 2.2.1 on 2019-11-19 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='event',
            new_name='activity',
        ),
    ]
