# Generated by Django 2.2.1 on 2019-11-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191118_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='admin',
            new_name='user',
        ),
    ]
