# Generated by Django 2.2.1 on 2019-11-24 02:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191118_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='activities',
        ),
        migrations.AddField(
            model_name='activity',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='fans', to=settings.AUTH_USER_MODEL),
        ),
    ]
